# Generated by Django 2.2.8 on 2020-08-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
